# Generated by Django 5.2.1 on 2026-03-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardCard',
        ),
    ]
