# Generated by Django 5.2.1 on 2026-03-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_dashboardcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.invoice'),
        ),
        migrations.DeleteModel(
            name='IncidentRequest',
        ),
    ]
