# Generated by Django 5.2.1 on 2026-03-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_invoice_project_project_invoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstage',
            options={'ordering': ['phase_number', 'sequence_order']},
        ),
        migrations.AddField(
            model_name='projectstage',
            name='phase_number',
            field=models.IntegerField(default=1),
        ),
    ]
