# Generated by Django 5.2.1 on 2026-03-10 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_start_date_client_address_client_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Flagged', 'Flagged')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='api.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Refund', 'Refund'), ('Missing', 'Missing'), ('Damaged', 'Damaged'), ('Exchange', 'Exchange')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.incident')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoiceitem')),
            ],
        ),
    ]
