# Generated by Django 5.2.1 on 2026-03-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_incident_incidentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='incident_attachments/'),
        ),
    ]
